Add source cluster extension jar page DMT phase 2
hazelcast/hz-docs pull request #1042
Opened 2024-03-04 22:23 UTC by srknzl

Extends https://github.com/hazelcast/hz-docs/pull/936/files to add DMT source cluster extension jar page. @rebekah-lawrence  Feel free to update the content and merge into your PR.

2024-03-06 10:11 UTC, rebekah-lawrence requested changes
Thanks Serkan!

2024-03-06 10:11 UTC, rebekah-lawrence commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +For each member in your cluster:
```suggestion
To use the extension JAR, complete the following steps for each member in your cluster:
```

2024-03-06 10:11 UTC, rebekah-lawrence commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +You can extend your source cluster by gracefully shutting down your cluster members one by one as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown, window=_blank]
```suggestion

```

2024-03-06 10:11 UTC, rebekah-lawrence commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +. Gracefully shutdown the member.
```suggestion
. Gracefully shutdown the member, as described in xref:maintain-cluster:shutdown.adoc#graceful-shutdown[Graceful Shutdown].
+
Once the graceful shutdown has completed, the cluster contains one less member but no data loss occurs.
```

2024-03-06 10:11 UTC, rebekah-lawrence commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +. After graceful shutdown, you will have one less member without any data loss. Add the extension jar to the class path of the JVM. You can use the _user-lib_ folder in your Hazelcast distribution ex
```suggestion
. Add the extension JAR to the class path of the JVM. 
+
You can use the _user-lib_ folder in your Hazelcast distribution to do this, as described in xref:clusters:deploying-code-from-clients.adoc#adding-user-library-to-classpath[Deploying User Code from Clients].
```

2024-03-08 20:26 UTC, srknzl reviewed
applied your changes + and also made it simpler because now we will require the extension only if the version is older than 5.3.7 for both APIs

2024-03-08 20:26 UTC, srknzl commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +Depending on which data structures you want to migrate, you may not need the extension jar.
applied slightly changed because 5.3.7 will have both APIs

2024-03-08 20:26 UTC, srknzl commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +Therefore, you need the extension jar if one of the following is true:
will actually delete these as they are duplicate data

2024-03-08 20:26 UTC, srknzl commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +* You want to migrate ReplicatedMap metadata and your source cluster version is not newer than "5.3.7". (This API is added to Hazelcast in "5.3.7".)
as said, will be deleted due to duplicate of above info

2024-03-08 20:26 UTC, srknzl commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +* You want to migrate CP structures (IAtomicLong, IAtomicReference, ICountdownLatch) and your source cluster is not newer than "5.4.0". (This API is added to Hazelcast in "5.4.0".) so if your source
as said, will be deleted due to duplicate of above info

2024-03-08 20:26 UTC, srknzl commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +WARNING: Using the extension jar with a Hazelcast versions that already have the API in the extension jar can cause a class mismatch and thus failures in migration. Therefore, don't use the extension
applied slightly differently due to general refactor

2024-03-11 08:50 UTC, rebekah-lawrence approved these changes
One small change to the warning; otherwise LGTM.

I'll make sure the rest of the files are updated in-line.

2024-03-11 08:50 UTC, rebekah-lawrence commented on docs/modules/migrate/pages/dmt-source-cluster-extension.adoc
> +WARNING: If your source cluster is newer than 5.3.7, you must not use the extension JAR since the APIs in the extension JAR already exists. If you use the extension JAR with a version of Hazelcast th
```suggestion
WARNING: Do not add the extension JAR if you are using version 5.3.7, or later. Data mismatches and migration failure can occur if you use the extension JAR with a version of Hazelcast that includes the API that replaces the extension JAR.
```

2024-03-11 23:12 UTC, srknzl commented
@rebekah-lawrence as i said on last weekly, can we merge this in your PR? You can just integrate this file to your PR. Applied your last suggestion as well.

2024-03-13 01:35 UTC, srknzl commented
yes, thanks

2024-03-13 01:35 UTC, closed without merging