RN for v5.4.0
hazelcast/hz-docs pull request #1050
Opened 2024-03-11 07:45 UTC by Serdaro

2024-03-11 09:43 UTC, rebekah-lawrence reviewed
Just a small change for UCN

2024-03-11 09:43 UTC, rebekah-lawrence commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* [.enterprise]*Enterprise* **User Code Namespaces**: Enable deployment, undeployment and redeployment of your custom classes. See the xref:clusters:user-code-namespaces.adoc[User Code Namespaces doc
```suggestion
* [.enterprise]*Enterprise* **User Code Namespaces**: Enable deployment and redeployment of your custom classes. See the xref:clusters:user-code-namespaces.adoc[User Code Namespaces documentation].
```

2024-03-13 09:34 UTC, oliverhowell approved these changes
Adding suggestion for TPC going GA - can you review and add @Serdaro ?

2024-03-13 09:34 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* [.enterprise]*Enterprise* **User Code Namespaces**: Enable deployment and redeployment of your custom classes. See the xref:clusters:user-code-namespaces.adoc[User Code Namespaces documentation].
```suggestion
* [.enterprise]*Enterprise* **User Code Namespaces**: Enable deployment and redeployment of your custom classes. See the xref:clusters:user-code-namespaces.adoc[User Code Namespaces documentation].
* [.enterprise]*Enterprise* **Thread-Per-Core (TPC)**: TPC now generally available. You can enable this on clients and cluster members for improved performance. See the xref:cluster-performance:thread-per-core-tpc.adoc[Thread-Per-Core (TPC) documentation].
```

2024-03-13 11:47 UTC, vbekiaris requested changes

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +** `SetGetAllMessageTask`: `iterator` -> `SecurityInterceptorConstants.GET_ALL`
This change was subsequently reverted in https://github.com/hazelcast/hazelcast/pull/25551. Can you please check and amend the list?

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* Fixed an issue where Hazelcast was not fast-failing when a member is started with a blank public address. This has been fixed by introducing a configuration validation
```suggestion
* Fixed an issue where Hazelcast was not failing fast when a member is started with a blank public address. This has been fixed by introducing a configuration validation
```
?

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* [.enterprise]*Enterprise* Tiered Store can now be used for map loaders.
```suggestion
* [.enterprise]*Enterprise* Tiered Store can now be used with map loaders.
```

Previously we wouldn't allow a map configured with a map store to be also configured with tiered storage. Now users can enable both tiered storage AND a map store for an IMap.

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* Added support of specifying the maximum size of a CPMap.
I think this and the following item can be skipped - they are just parts of introducing the CPMap data structure.

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* Implemented RAFT lifecycle interfaces for CPMap. #6800
This item is also just normal part of implementing a CP data structure, so nothing notable for users to see, I 'd rather remove it.

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* [.enterprise]*Enterprise* Added the ability to check whether the `ADVANCED_CP` feature is present in the Hazelcast Platform Enterprise license, to enable CPMap. #157
just a license check PR, not RN-worthy I think. The requirements for using CPMap are anyway listed in the CPMap documentation page.

2024-03-13 11:47 UTC, vbekiaris commented on docs/modules/release-notes/pages/5-4-0.adoc
> +* Added support for configuration of `CLASS` type resources for user code namespaces. #702
Not RN-worth, just part of UCN implementation

2024-03-13 13:14 UTC, kwart commented on docs/modules/release-notes/pages/5-4-0.adoc
> +** `TransactionalMultiMapRemoveEntryMessageTask`: `removeEntry` -> `SecurityInterceptorConstants.REMOVE`
```suggestion
* Method names used as parameters in https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/security/SecurityInterceptor.html[`SecurityInterceptor`] checks were reviewed and unified into a single place  - class `com.hazelcast.security.SecurityInterceptorConstants`. Some client messages have the method name changed to reflect their purpose better. Some client messages are newly covered by `SecurityInterceptor` checks now.
```

Here is the list of message tasks that have the value changed in `5.4.0`:
```
TransactionalListAddMessageTask.java
ReplicatedMapAddNearCacheListenerMessageTask.java
MapDestroyCacheMessageTask.java
MapAddNearCacheInvalidationListenerMessageTask.java
AbstractMapPartitionMessageTask.java
MapFetchWithQueryMessageTask.java
MapFetchEntriesMessageTask.java
MapAddListenerMessageTask.java
MapProjectionWithPredicateMessageTask.java
ScheduledExecutorSubmitToPartitionMessageTask.java
ScheduledExecutorTaskGetResultFromTargetMessageTask.java
ScheduledExecutorSubmitToTargetMessageTask.java
ScheduledExecutorGetAllScheduledMessageTask.java
ScheduledExecutorTaskGetResultFromPartitionMessageTask.java
ListGetAllMessageTask.java
XATransactionCommitMessageTask.java
XATransactionPrepareMessageTask.java
XATransactionRollbackMessageTask.java
TransactionCommitMessageTask.java
TransactionCreateMessageTask.java
XATransactionCreateMessageTask.java
XAClearRemoteTransactionMessageTask.java
TransactionRollbackMessageTask.java
XACollectTransactionsMessageTask.java
XAFinalizeTransactionMessageTask.java
PNCounterGetConfiguredReplicaCountMessageTask.java
CacheSizeMessageTask.java
CacheListenerRegistrationMessageTask.java
TransactionalMapSizeMessageTask.java
CacheListenerRegistrationMessageTask.java
CacheDestroyMessageTask.java
CacheGetAndReplaceMessageTask.java
CacheManagementConfigMessageTask.java
CacheAddPartitionLostListenerMessageTask.java
CacheAddEntryListenerMessageTask.java
CacheRemoveInvalidationListenerMessageTask.java
CacheRemovePartitionLostListenerMessageTask.java
CacheCreateConfigMessageTask.java
CacheLoadAllMessageTask.java
CacheGetConfigMessageTask.java
DestroyProxyMessageTask.java
ExecutorServiceSubmitToPartitionMessageTask.java
ExecutorServiceSubmitToAddressMessageTask.java
DurableExecutorRetrieveAndDisposeResultMessageTask.java
DurableExecutorSubmitToPartitionMessageTask.java
DurableExecutorDisposeResultMessageTask.java
DurableExecutorRetrieveResultMessageTask.java
CreateProxyMessageTask.java
TransactionalMultiMapRemoveEntryMessageTask.java
AbstractMultiTargetMessageTask.java
CreateProxiesMessageTask.java
```

2024-03-14 09:23 UTC, vbekiaris approved these changes

2024-03-14 09:27 UTC, merged