Clarification about client use public ip property
hazelcast/hz-docs pull request #1108
Opened 2024-05-08 10:35 UTC by srknzl

See https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1715012564100079

the property is not described well enough. in this pr I am fixing this.

2024-05-08 11:11 UTC, rebekah-lawrence requested changes

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +depending on your setup. See the <<client-system-properties, Client System Properties section>> for the description of
```suggestion
to suit your setup. For further information on the `hazelcast.discovery.public.ip.enabled` property, see <<client-system-properties, Client System Properties>>. 
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +the `hazelcast.discovery.public.ip.enabled` property.
```suggestion

```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +In case you are not providing an address list,
```suggestion
If you use a <<client-network,discovery mechanism>> to find the initial member for the connection instead of an address list,
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +but using a <<client-network, discovery mechanism>> to find the initial member to connect to,
```suggestion

```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +above property also applies to the initial member connection private vs public address selection decision.
```suggestion
you can use the same property to configure whether the initial member connection uses the private or public address.
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +For an example of this scenario, you can have a look at
```suggestion
For an example of this scenario, refer to
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +xref:hazelcast-platform-operator-expose-externally.adoc[Connect to Hazelcast from Outside Kubernetes] guide.
```suggestion
xref:hazelcast-platform-operator-expose-externally.adoc[Connect to Hazelcast from Outside Kubernetes, window=_blank] in the Operator documentation.
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +|Overrides client behaviour when choosing between using public or private addresses of members.
```suggestion
|Overrides client behavior when the member has both public and private addresses available.
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +This inference is not %100 reliable and may result in false-negatives. Thus, it's advised to override this
```suggestion
As the client's inference is not 100% reliable and can result in false-negatives, we recommend that it is overridden by
```

2024-05-08 11:11 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +to `true` if it's known that the client will not be able to connect to members via their public addresses.
```suggestion
setting to `true` when the client cannot connect to members using their public addresses.
```

2024-05-08 12:02 UTC, ihsandemir commented on docs/modules/clients/pages/java.adoc
> +The initial connection of a client will be established using one of the addresses you provide in the <<configuring-address-list, address list>>.
this is not correct! unisocket also uses the configured list.

2024-05-08 12:02 UTC, ihsandemir commented on docs/modules/clients/pages/java.adoc
> +In case your client is <<java-client-operation-modes, smart>>, the client will then get the addresses of other members in the cluster and try to connect to them.
not correct! unisocket gets the members as well but only connects to one member.

2024-05-08 12:40 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +In case your client is <<java-client-operation-modes, smart>>, the client will then get the addresses of other members in the cluster and try to connect to them.
ok this is acceptable, will reword it

2024-05-08 12:51 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +to `true` if it's known that the client will not be able to connect to members via their public addresses.
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:52 UTC, ihsandemir commented on docs/modules/clients/pages/java.adoc
> +The initial connection of a client will be established using one of the addresses you provide in the <<configuring-address-list, address list>>.
sorry, mixed with other comment.

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +In case you are not providing an address list,
https://github.com/hazelcast/hz-docs/pull/1108/commits/03baba7f36998a8bb8979e6f6122aac48fe7aa20

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +In case your client is <<java-client-operation-modes, smart>>, the client will then get the addresses of other members in the cluster and try to connect to them.
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +If any of those members has private & public addresses at the same time, the client needs to decide
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +which one it should use to connect to those members. You may want to override the property `hazelcast.discovery.public.ip.enabled`
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +depending on your setup. See the <<client-system-properties, Client System Properties section>> for the description of
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +the `hazelcast.discovery.public.ip.enabled` property.
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:56 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +but using a <<client-network, discovery mechanism>> to find the initial member to connect to,
https://github.com/hazelcast/hz-docs/pull/1108/commits/4ea9d9f7d6b4ba94436650831011aa4c27bfaa50

2024-05-08 12:58 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +For an example of this scenario, you can have a look at
14bc3591

2024-05-08 12:59 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +If your client is <<java-client-operation-modes, smart>>, the client tries to connect to them.
this is not important though, I am mentioning a scenario that only applies to smart

2024-05-08 13:01 UTC, srknzl commented
thanks for the reviews 🙏🏻 

@rebekah-lawrence hopefully I didn't make a mistake, I should have done applied via github UI maybe. I manually edited files, so if I missed any of the changes, please tell me. You can go over once more to ensure that didn't happen

2024-05-08 13:12 UTC, rebekah-lawrence approved these changes
No worries, I tend to update the files manually and it can make it harder to ensure you've caught everything at times - but I think you did. 

Just a couple of small amendments; other than that LGTM, so approving in advance.

Thanks!

2024-05-08 13:12 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +which one to use when connecting to those members. You can override the property `hazelcast.discovery.public.ip.enabled` property
```suggestion
which one to use when connecting to those members. You can override the `hazelcast.discovery.public.ip.enabled` property 
```

2024-05-08 13:12 UTC, rebekah-lawrence commented on docs/modules/clients/pages/java.adoc
> +see <<client-system-properties, Client System Properties section>>.
```suggestion
see <<client-system-properties, Client System Properties>>.
```

2024-05-08 13:15 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +If your client is <<java-client-operation-modes, smart>>, the client tries to connect to them.
@ihsandemir please note that "them" in this sentence means other members other than initial member

2024-05-08 13:19 UTC, srknzl commented on docs/modules/clients/pages/java.adoc
> +If your client is <<java-client-operation-modes, smart>>, the client tries to connect to them.
which means we cant say "if the client is in unisocket mode, it will connect to only one of them in a random way." because it's wrong

2024-06-04 13:31 UTC, srknzl commented
@ihsandemir can you have a look at this again pls?

2024-06-13 17:16 UTC, merged