Add note to adv network configuration docs w.r.t endpoint overlaps
hazelcast/hz-docs pull request #1147
Opened 2024-06-26 14:08 UTC by JamesHazelcast

This addition is made following an incident that raised the topic for discussion.

See: https://hazelcast.atlassian.net/browse/SUP-432

2024-06-26 14:08 UTC, JamesHazelcast commented
Relevant slack discussion: https://hazelcast.slack.com/archives/C07A6AD6KGQ/p1719404769515719

2024-06-27 07:17 UTC, rebekah-lawrence requested changes
Slight changes; I removed the bold from the note - honestly, even if we put it in flashing lights, scrolling across the screen, and with funky music, people either read it or they don't.

I have also added the Backport to 5.4 label to automatically add the change to the 5.4 doc set as well; if this doesn't need to be backported (but it looks like it does from the linked ticket), you can remove it.

2024-06-27 07:17 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/network-configuration.adoc
> +`WAN` and `MEMBER` protocols, it is important to **ensure that endpoint ranges do not overlap**.
```suggestion
`WAN` and `MEMBER` protocols, you must ensure that endpoint ranges do not overlap.
```

2024-06-27 07:17 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/network-configuration.adoc
> +Each protocol should be configured with unique endpoints that are not used in other protocols,
```suggestion
Each protocol must be configured with unique endpoints that are not used in other protocols,
```

2024-06-27 07:17 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/network-configuration.adoc
> +otherwise WAN replication in environments where IPs are reused may cause the cluster to
```suggestion
otherwise WAN replication can cause the cluster to
```

2024-06-27 07:17 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/network-configuration.adoc
> +become unstable.
```suggestion
become unstable if IPs are reused.
```

2024-06-27 10:03 UTC, rebekah-lawrence approved these changes
LGTM

Thanks, as always @JamesHazelcast

2024-06-27 11:20 UTC, merged