Thin Java Client page added
hazelcast/hz-docs pull request #1167
Opened 2024-07-08 13:18 UTC by sergey-serdyukov

For release 5.5

2024-07-08 13:18 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org:443/pull/badge/not_signed)](https://cla.hazelcast.org:443/hazelcast/hz-docs?pullRequest=1167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org:443/hazelcast/hz-docs?pullRequest=1167) before we can accept your contribution.<br/><hr/>**Alexey Agapov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org:443/check/hazelcast/hz-docs?pullRequest=1167) it.</sub>

2024-07-26 13:36 UTC, rebekah-lawrence reviewed
Please sign the CLA.

I have reviewed as far as I can. Please try to apply the spirit of the comments to the remainder of the page.

2024-08-01 11:46 UTC, oliverhowell requested changes
Hey Sergey, did you get a chance to review Rebekah's comments and make changes?

2024-08-01 14:49 UTC, sergey-serdyukov commented on .gitignore
> +*.html
You are right! This should be removed, it is left over from experiments. Thanks for noticing!

2024-08-01 16:02 UTC, sergey-serdyukov commented on docs/modules/clients/pages/java-thin-client.adoc
> +You can configure Hazelcast Thin Java Client declaratively (XML), programmatically (API), or
I'll double check. Good point

2024-08-01 16:15 UTC, sergey-serdyukov commented on docs/modules/clients/pages/java-thin-client.adoc
> +You can configure Hazelcast Thin Java Client declaratively (XML), programmatically (API), or
Or just leave the NOTE with "not supported"?

2024-08-01 16:23 UTC, sergey-serdyukov commented on docs/modules/clients/pages/java-thin-client.adoc
> +All network related configuration of Hazelcast Thin Java Client is performed in the class
Java Thin Client sounds good unless someone comes up with a better name

2024-08-01 18:21 UTC, sergey-serdyukov commented on docs/modules/clients/partials/nav.adoc
> +** xref:clients:java-thin-client.adoc[]
Done

2024-08-02 09:12 UTC, sergey-serdyukov commented on docs/modules/clients/pages/java-thin-client.adoc
> += Thin Java Client
Planning to split the page in the nearest future.

2024-08-02 10:15 UTC, sergey-serdyukov commented on docs/modules/clients/pages/java-thin-client.adoc
> +If your client is <<java-client-operation-modes, smart>>, the client tries to connect to them.
It has been removed. In the future we will review the usage of connection modes.

2024-08-02 13:33 UTC, sergey-serdyukov commented
> Hey Sergey, did you get a chance to review Rebekah's comments and make changes?

Hi @oliverhowell , yes Rebekah's comments were helpful, all changes have been made. I'll close this PR to simplify rebase as it was opened long ago and there are many other changes. Gonna to send another PR shortly (with the same changes).

2024-08-02 13:33 UTC, closed without merging