Add vector collection metrics documentation [AI-52]
hazelcast/hz-docs pull request #1171
Opened 2024-07-09 11:54 UTC by k-jamroz

Documentation for metrics added in https://github.com/hazelcast/hazelcast-mono/pull/2471

2024-07-10 12:22 UTC, vbekiaris approved these changes

2024-07-18 14:50 UTC, oliverhowell requested changes
Thanks @vbekiaris - only minor changes (the whole page could do with a thorough review and edit tbh) but I've suggested changes.

2024-07-18 15:21 UTC, k-jamroz commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +We recommend monitoring the average latency for each operation, for example, `vectorCollection.totalGetLatency` / `vectorCollection.getCount` and `vectorCollection.totalSetLatency` / `vectorCollectio
`/` here is division to calculate average latency

2024-07-18 15:23 UTC, k-jamroz commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +Increased average latency is a sign that the cluster would experience performance problems, or there is a spike in the load.
I copied this section from IMap above. Same fixes should be done there

2024-07-18 15:26 UTC, k-jamroz commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +The above `*latency` metrics are only measured for the members and they are not representing the overall performance of the cluster.
`*latency` is a wildcard matching everything that ends with "latency", but without star it is also ok. but the same adjustments should be made for IMap metrics description

2024-07-19 10:24 UTC, k-jamroz commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +We recommend monitoring the average latency for each operation, for example, `vectorCollection.totalGetLatency` / `vectorCollection.getCount` and `vectorCollection.totalSetLatency` / `vectorCollectio
```suggestion
We recommend monitoring the average latency for each operation, for example, `vectorCollection.totalGetLatency / vectorCollection.getCount` and `vectorCollection.totalSetLatency / vectorCollection.setCount`.
```

2024-07-19 10:29 UTC, k-jamroz commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +We recommend monitoring the average latency for each operation, for example, `vectorCollection.totalGetLatency` / `vectorCollection.getCount` and `vectorCollection.totalSetLatency` / `vectorCollectio
changed to single expressions: https://github.com/hazelcast/hz-docs/pull/1171/commits/e2ec2a42f996b25786c6e2ff7eec1f717dbfdfaa

2024-07-19 10:51 UTC, oliverhowell commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +The above `*latency` metrics are only measured for the members and they are not representing the overall performance of the cluster.
Ah, I thought that was mistake with bold formatting perhaps - ignore my suggestion

2024-07-19 10:53 UTC, oliverhowell commented on docs/modules/ROOT/pages/list-of-metrics.adoc
> +We recommend monitoring the average latency for each operation, for example, `vectorCollection.totalGetLatency` / `vectorCollection.getCount` and `vectorCollection.totalSetLatency` / `vectorCollectio
Thanks, that helps - "/" is not always used to mean divide but I guess in this context it's pretty clear (though I missed it on first skim reading).

2024-07-19 10:54 UTC, oliverhowell approved these changes

2024-07-19 11:35 UTC, merged