Remove twitter and redis connectors
hazelcast/hz-docs pull request #1172
Opened 2024-07-09 18:21 UTC by TomaszGaweda

2024-07-11 13:46 UTC, oliverhowell requested changes
Hello @TomaszGaweda, thanks for raising this - can you add the following entry to your connectors.adoc file too to cover any redirects? (Last 2 entries are new)

:page-aliases: sql:connectors.adoc, pipelines:sources-sinks.adoc, integrate:redis-connector.adoc, integrate:twitter-connector.adoc

2024-07-11 14:14 UTC, TomaszGaweda commented
Very good point @oliverhowell, done

2024-07-12 13:20 UTC, oliverhowell approved these changes

2024-07-12 13:20 UTC, merged

2024-07-12 13:21 UTC, oliverhowell commented
Great, thanks @TomaszGaweda