Fix jetty plugin documentation link
hazelcast/hz-docs pull request #1189
Opened 2024-07-22 11:12 UTC by srknzl

The old link redirects to https://jetty.org/docs/

Feel free to change the new link, I'm not sure if we should give a link to 12. Using latest in the link does not work

2024-07-22 15:14 UTC, rebekah-lawrence commented
Hi @srknzl I've added the back/forward port labels so the update is included in all versions.

On the link - is 12 the version Hz recommends/uses, or can any version be used? If the former, leave the direct link to 12; otherwise, just link to https://jetty.org/docs/ and let the user select the version they need.

2024-07-23 08:53 UTC, srknzl commented
> Hi @srknzl I've added the back/forward port labels so the update is included in all versions.
> 
> On the link - is 12 the version Hz recommends/uses, or can any version be used? If the former, leave the direct link to 12; otherwise, just link to https://jetty.org/docs/ and let the user select the version they need.

I don't think we have a version we recommend. However, the downside of providing link to https://jetty.org/docs/ is that the link is so general and not related to Hazelcast. We should additional instructions for user such as: "for documentation, search for Hazelcast in jetty docs" etc

wdyt?

2024-07-23 09:41 UTC, rebekah-lawrence commented
Looking at the jetty docs, Hazelcast is only specifically mentioned in 12 - so, it is probably best to keep the link direct to the pertinent information. 

Or, we fork their documentation and configure a latest path... 😇 🤣

2024-07-23 09:43 UTC, rebekah-lawrence requested changes

2024-07-23 09:43 UTC, rebekah-lawrence commented on docs/modules/plugins/pages/web-session-replication.adoc
> +See the https://jetty.org/docs/jetty/12/operations-guide/session/index.html#hazelcast[Jetty: Persistent Sessions with Hazelcast^]
```suggestion
For further information, refer to https://jetty.org/docs/jetty/12/operations-guide/session/index.html#hazelcast[Persistent Sessions with Hazelcast^] in the Jetty documentation.
```

2024-07-24 09:17 UTC, srknzl commented
@rebekah-lawrence I see https://jetty.org/docs/jetty/11/operations-guide/session/index.html#hazelcast as well. I think it's not only jetty 12 Hazelcast mentioned in

2024-08-09 17:36 UTC, oliverhowell approved these changes

2024-10-02 11:44 UTC, merged