[CN-127] Add Expose Externally to Hazelcast Enterprsie Operator deplo…
hazelcast/hz-docs pull request #132
Opened 2021-08-25 13:44 UTC by leszko

…yment

2021-08-31 14:52 UTC, Serdaro approved these changes

2021-09-01 10:03 UTC, JakeSCahill requested changes

2021-09-01 10:03 UTC, JakeSCahill commented on docs/modules/deploy/pages/deploying-with-operator.adoc
> +* `memberAccess`: the way how each Hazelcast member is accessed
```suggestion
* `memberAccess`: The way in which clients access Hazelcast members.
```

2021-09-01 11:39 UTC, leszko commented on docs/modules/deploy/pages/deploying-with-operator.adoc
> +** `NodePortNodeName`: Hazelcast client is inside the same network as the Kubernetes nodes, so members can access Kubernetes nodes by their hostnames
yes

2021-09-01 12:50 UTC, JakeSCahill commented on docs/modules/deploy/pages/deploying-with-operator.adoc
> +** `NodePortNodeName`: Hazelcast client is inside the same network as the Kubernetes nodes, so members can access Kubernetes nodes by their hostnames
```suggestion
** `NodePortNodeName`: Hazelcast clients are inside the same network as the Kubernetes nodes, so clients can access a member by the hostname of its Kubernetes node.
```

2021-09-01 12:52 UTC, JakeSCahill approved these changes
Looks good, thanks @leszko 

I'd just clarify the point about addressing members by their Kubernetes hostnames.

2021-09-01 14:35 UTC, merged