DOC-191: Add Ask AI page
hazelcast/hz-docs pull request #1343
Opened 2024-10-22 12:03 UTC by oliverhowell

Adds Ask AI page to nav so it features prominently and also provides some detail and tips.

Backport strategy TBD but we can replicate this page in each of the other products too (initially the same but can always diverge in future and e.g. make tips more MC appropriate).

- [ ] Decide what versions we backport to

2024-10-22 15:09 UTC, amandalindsay requested changes
tiny tweak, otherwise looks good!

2024-10-23 12:47 UTC, oliverhowell commented
Backporting: let's see if the backport to 5.5 works ok and then add a separate release notes entry to 5.5 branch

2024-10-23 13:04 UTC, amandalindsay approved these changes

2024-11-01 13:46 UTC, oliverhowell commented
I replaced the gif with a couple of images - on reflection I think it's not worth the extra file size in this context.

2024-11-01 13:49 UTC, merged