Add documentation for using DataConnectionService [SUP-523]
hazelcast/hz-docs pull request #1361
Opened 2024-11-04 15:48 UTC by frant-hartm

2024-11-04 15:52 UTC, frant-hartm commented
@oliverhowell @amandalindsay Before jumping on this one, it might be worth waiting to have devs/QE to review it first - I am not 100 % sure it's all understandable.

2024-11-20 11:43 UTC, frant-hartm commented on docs/modules/data-connections/pages/data-connection-service.adoc
> +== Typical Usage
5991a9b404a51ab618c1ea2a22d5f71dcf2cdc2a

2024-11-20 11:43 UTC, frant-hartm commented on docs/modules/data-connections/pages/how-to-map-loader-data-connection.adoc
> +|Java !! current java version !!
5991a9b404a51ab618c1ea2a22d5f71dcf2cdc2a

2024-11-22 12:02 UTC, Rob-Hazelcast requested changes
These look like well-structured procedures with prerequisites, numbered steps etc. There are a handful of bugs and inconsistencies, and a few bits I'd like to see fleshed out for improved usability.

2024-11-28 13:45 UTC, frant-hartm commented on docs/modules/data-connections/pages/data-connection-service.adoc
> +== Retrieve Data Connection Service
Yes, these sections provide more details.

2024-11-29 10:15 UTC, frant-hartm commented on docs/modules/data-connections/pages/how-to-map-loader-data-connection.adoc
> +----
245266b

2024-11-29 10:15 UTC, frant-hartm commented on docs/modules/data-connections/pages/how-to-pipeline-service-data-connection.adoc
> +-- takes a sequence of numbers
330acb1

2024-11-29 16:13 UTC, Rob-Hazelcast commented on docs/modules/data-connections/pages/data-connection-service.adoc
> +.adoc). In such cases, the DataConnection instance will stay valid until you release it, allowing you to retrieve the underlying resource as needed. This approach can be useful for adapting to change
Still broken. I don't see a sql.adoc in the repo. I think you want create-data-connection.adoc.

2024-11-29 16:18 UTC, Rob-Hazelcast commented on docs/modules/data-connections/pages/data-connection-service.adoc
> +:description: Using the Data Connection Service gives access to the configured data connections in custom components.
Not if you don't add them to the right place in nav.adoc

2024-11-29 16:20 UTC, Rob-Hazelcast reviewed
Looking much better, just a couple of outstanding issues. Most important is to reference the new files in nav.adoc. It would be nice to have a validation rule for this @oliverhowell!

2024-12-04 13:29 UTC, ollyhowell approved these changes

2024-12-04 13:46 UTC, TomaszGaweda approved these changes

2024-12-04 13:55 UTC, Rob-Hazelcast approved these changes

2024-12-04 13:55 UTC, merged