Add jet migration guide
hazelcast/hz-docs pull request #175
Opened 2021-09-09 15:00 UTC by JakeSCahill

Fixes #162 and #163

2021-09-10 14:33 UTC, vladoschreiner requested changes
I can't locate the entry point to the Jet migration guide in the Netlify preview.

2021-09-10 14:48 UTC, vladoschreiner commented on docs/modules/migrate/pages/upgrading-from-jet.adoc
> +In embedded mode (Hazelcast as a classic Java process), Jet is disabled by default. As a result, you cannot use Jet APIs or SQL unless you enable the Jet engine.
Hazelcast always runs as a Java process. The embedded mode refers to "Hazelcast running in the JVMs of your application" as opposed to "Hazelcast running in its own standalone JVMs.

2021-09-10 14:53 UTC, vladoschreiner commented on docs/modules/migrate/pages/upgrading-from-jet.adoc
> +Hazelcast {page-component-version} *is not* compatible with any other aspects of Jet 4.x. You cannot upgrade using rolling upgrades and you cannot connect to the cluster using version 4.x of clients)
Please be more specific:
- I can't do rolling upgrade, that is clear. I must do a down-time upgrade.
- Can I move the Job to from Jet 4 to Hz 5 by copying the job snapshot? Are jobs snapshot-compatible?
- Can I connect to Hz 5 cluster using Jet 4 client? Or do I have to upgrade the version of my client libs?

2021-09-10 14:54 UTC, vladoschreiner commented on docs/modules/migrate/pages/upgrading-from-jet.adoc
> +For a complete list of contents in each distribution, see xref:deploy:installing-upgrading.adoc#full-and-slim-packages[Full and Slim Packages].
Please provide an action point. Does the distribution change require my attention?

2021-09-14 21:24 UTC, ufukyilmaz commented on docs/modules/migrate/pages/upgrading-from-jet.adoc
> +The link:https://jet-start.sh/javadoc/4.5/com/hazelcast/jet/config/InstanceConfig.html[`InstanceConfig` object] has been removed and all its methods have been added to the `JetConfig` object.
it's been deprecated and will be removed in a future release (it's not removed yet).

2021-09-15 14:41 UTC, vladoschreiner approved these changes

2021-09-15 15:51 UTC, merged