DOC-216 Adds HZ Cloud attr to playbooks and to pages
hazelcast/hz-docs pull request #480
Opened 2022-07-07 12:34 UTC by angelasimms

Changes:

- Attribute and value added to 2x Antora playbook files
- Attribute added to relevant pages

2022-07-07 14:28 UTC, JakeSCahill approved these changes

2022-08-18 17:11 UTC, JakeSCahill requested changes

2022-08-19 08:06 UTC, angelasimms commented on docs/modules/clients/pages/clc.adoc
> +      token: "HAZELCAST VIRIDIAN TOKEN"
Updated as requested.

2022-08-19 08:08 UTC, angelasimms commented on antora-playbook-local.yml
> +    hazelcast-cloud: Hazelcast Viridian
I think I have updated this correctly but sometimes it is more difficult to see whether Hazelcast Viridian or Hazelcast Viridian Managed Services might be more appropriate. Anyway, let me know what you think.

2022-09-13 09:48 UTC, JakeSCahill approved these changes

2022-09-13 09:48 UTC, merged