Add Node.js client codes for entry listeners with predicates [API-1484]
hazelcast/hz-docs pull request #503
Opened 2022-08-17 12:21 UTC by fatihozer0

2022-08-31 11:15 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +}
This is not valid Node.js:

![image](https://user-images.githubusercontent.com/32355782/187666111-3a42dc53-cc08-4a15-8c4f-53b289d41f62.png)

2022-08-31 11:15 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +--
Please revert these unnecessary changes.

2022-08-31 11:16 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +}
```suggestion
};
```

2022-08-31 11:17 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +await map.addEntryListenerWithPredicate(listener, new Predicates.sql('surname = smith'), undefined, true);
```suggestion
await map.addEntryListenerWithPredicate(listener, new Predicates.sql('surname=smith'), undefined, true);
```

2022-08-31 11:19 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +        console.log('Entry added: ' + entryEvent.value);
technically value is not entry. can you print both key and value with something like: (in backticks) `key: ${entryEvent.key}, value: ${entryEvent.value}`

2022-08-31 11:20 UTC, srknzl commented on docs/modules/data-structures/pages/listening-for-map-entries.adoc
> +const client = await Client.newHazelcastClient();
One thing I noticed, Java provides whole working code sample. Can you also do the same? Example:

```js
const { Client, Predicates } = require('hazelcast-client');

async function main() {
    const client = await Client.newHazelcastClient();
    const map = await client.getMap('map');
    const listener = {
        added: (entryEvent) => {
            console.log('Entry added: ' + entryEvent.value);
        },
        removed: (entryEvent) => {
            console.log('Entry removed: ' + entryEvent.value);
        },
        updated: (entryEvent) => {
            console.log('Entry updated: ' + entryEvent.value);
        }
    };
    await map.addEntryListenerWithPredicate(listener, new Predicates.sql('surname = smith'), undefined, true);
    console.log('Entry listener registered');
    await client.shutdown();
}

main().catch(err => {
    console.error('Error occurred:', err);
    process.exit(1);
});

```

2022-08-31 11:21 UTC, srknzl requested changes
Requested some changes.

2022-09-01 08:18 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hz-docs?pullRequest=503) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hz-docs?pullRequest=503) before we can accept your contribution.<br/>**12** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: mdumandag<br/>:white_check_mark: Serdaro<br/>:white_check_mark: JakeSCahill<br/>:white_check_mark: promanenko<br/>:white_check_mark: jerrinot<br/>:white_check_mark: mtyazici<br/>:white_check_mark: ldziedziul<br/>:white_check_mark: angelasimms<br/>:white_check_mark: emreyigit<br/>:white_check_mark: kwart<br/>:white_check_mark: Holmistr<br/>:white_check_mark: fatihozer0<br/>:x: devOpsHazelcast<br/>:x: sgandon<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hz-docs?pullRequest=503) it.</sub>

2022-09-01 08:35 UTC, srknzl commented
@fatihozer0 These 85 commits from several people looks problematic. Can you extract the required commits and only add them to this PR?

2022-09-01 11:49 UTC, fatihozer0 commented
PR is closed because of a mistake I've done. Continues here #520

2022-09-01 11:49 UTC, closed without merging