Document the JDBC SQL connector
hazelcast/hz-docs pull request #517
Opened 2022-08-30 13:57 UTC by JakeSCahill

2022-08-30 14:31 UTC, angelasimms commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +This connector is included in the full and slim distributions of Hazelcast.
```suggestion
The JDBC connector is included in the full and slim distributions of Hazelcast.
```

2022-08-30 14:35 UTC, angelasimms commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +** The full distribution comes with a JDBC driver for MySQL and PostgresSQL data stores.
```suggestion
** The full distribution of Hazelcast comes with a JDBC driver for MySQL and PostgreSQL data stores.
```

2022-08-30 14:35 UTC, angelasimms commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +** The slim distribution does not come with a JDBC driver.
```suggestion
** The slim distribution of Hazelcast does not come with a JDBC driver.
```

2022-08-30 14:37 UTC, angelasimms commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +CREATE TABLE (id INT PRIMARY KEY, name VARCHAR(100))
```suggestion
CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(100))
```

2022-08-30 15:22 UTC, angelasimms approved these changes
All looks good to me.

2022-08-30 16:00 UTC, JakeSCahill commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +:description: To query external data stores, you need to create a mapping with the JDBC connector so that the SQL service knows how to access the data store.
```suggestion
:description: To query external data stores, you can create a mapping to them with the JDBC connector.
```

2022-08-30 16:01 UTC, JakeSCahill commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +:description: To query external data stores, you can create a mapping to them with the JDBC connector.
```suggestion
:description: To query external data stores, you can create a mapping to them with the JDBC connector.
:page-beta: true
```

2022-08-31 13:28 UTC, frant-hartm requested changes

2022-08-31 14:07 UTC, JakeSCahill commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +== Creating a JDBC Mapping
We don't have a section about using the mapping or supported statements, but if there is a limited list of statements that you can use, we should definitely document those here. Do we have a list?

Also, are there any details that users need to be able to use the mapping?

2022-08-31 14:07 UTC, JakeSCahill commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +You then create the following `people` table:
```suggestion
You then create the following `people` table in the MySQL database:
```

2022-08-31 15:23 UTC, JakeSCahill commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +)
are there other options that are prefixed with `jdbc`?

2022-09-12 09:47 UTC, frant-hartm commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +)
At the moment there isn't.

2022-09-12 09:49 UTC, frant-hartm commented on docs/modules/sql/pages/mapping-to-jdbc.adoc
> +== Creating a JDBC Mapping
In 5.2 we support `SELECT`, `INSERT`, `UPDATE` and `DELETE`.

2022-09-14 21:25 UTC, frant-hartm approved these changes

2022-09-15 09:29 UTC, merged