Update go client samples after release [API-1813]
hazelcast/hz-docs pull request #667
Opened 2023-02-23 18:00 UTC by fatihozer0

2023-03-01 09:21 UTC, yuce commented
@fatihozer0 Could you check that the new example works?

2023-03-08 14:22 UTC, Serdaro commented
@fatihozer0 , I cannot validate if it works. Could you please let me know?

2023-03-10 15:07 UTC, mehmettokgoz commented on docs/modules/getting-started/pages/get-started-binary.adoc
>      // handle the error
We should either `panic(err)` inside if or remove these handlers and add `// error handling is omitted for brevity` warning after line 640.

2023-03-21 00:48 UTC, yuce commented
@fatihozer0 Could you try running the Go code in this PR and verify that it compiles / works OK?

2023-03-29 12:15 UTC, yuce requested changes

2023-03-30 11:57 UTC, fatihozer0 commented on docs/modules/getting-started/pages/get-started-binary.adoc
> +  ctx := context.TODO()
Done.

2023-03-31 18:43 UTC, yuce approved these changes
Looks good!

2023-04-03 06:10 UTC, merged