[CN-894] Add note about the recommended port name
hazelcast/hz-docs pull request #776
Opened 2023-06-19 13:21 UTC by SeriyBg

2023-06-19 15:22 UTC, semihbkgr approved these changes

2023-06-19 16:37 UTC, angelasimms requested changes
Minor rewording

2023-06-19 16:37 UTC, angelasimms commented on docs/modules/kubernetes/pages/kubernetes-auto-discovery.adoc
> +NOTE: If the Service is exposing multiple ports, it is recommended that you name the port that is exposing Hazelcast member as `hazelcast` in order for auto-discovery to function correctly.
```suggestion
NOTE: If the service exposes multiple ports, name the port that exposes the Hazelcast member `hazelcast`. This configuration ensures that auto-discovery functions correctly.
```
Just minor rewording.

2023-06-20 09:02 UTC, angelasimms approved these changes
LGTM

2023-06-25 13:57 UTC, merged