Add WAN eviction cluster properties
hazelcast/hz-docs pull request #802
Opened 2023-07-18 11:46 UTC by JamesHazelcast

We recently added 2 new `ClusterProperty` entries for 5.4 related to the replication of eviction events with `IMap` and `ICache`.

Relevant PR: https://github.com/hazelcast/hazelcast/pull/24941

2023-07-19 15:10 UTC, JamesHazelcast commented
This will also need backporting for the next `5.3.z` release as we are backporting this enhancement.

2023-07-21 10:59 UTC, angelasimms requested changes
Minor changes for clarity. Please let me know if there are any questions.

2023-07-21 10:59 UTC, angelasimms commented on docs/modules/ROOT/pages/system-properties.adoc
> +|Specifies whether `IMap` objects should replicate entry evictions over WAN to target clusters. When enabled, ALL evictions (size- or expiration-driven as well as manual invocation) are replicated to
```suggestion
|Specifies whether `IMap` objects replicate entry evictions over WAN to target clusters. Use this property with caution. When enabled, _ALL_ evictions, including size or expiration-driven evictions and manual invocations are replicated to target clusters. Setting this property to `true` does not guarantee data consistency between clusters.
```

2023-07-21 10:59 UTC, angelasimms commented on docs/modules/ROOT/pages/system-properties.adoc
> +|Specifies whether `ICache` objects should replicate entry evictions over WAN to target clusters. When enabled, ALL evictions (size- or expiration-driven as well as manual invocation) are replicated
```suggestion
|Specifies whether `ICache` objects replicate entry evictions over WAN to target clusters. Use this property with caution. When enabled, _ALL_ evictions, including size or expiration-driven evictions and manual invocations are replicated to target clusters. Setting this property to `true` does not guarantee data consistency between clusters.
```

2023-07-21 13:36 UTC, JamesHazelcast commented
> Minor changes for clarity. Please let me know if there are any questions.

Appreciate the feedback @angelasimms, definitely much more clear now, thank you 👍

2023-07-21 15:10 UTC, angelasimms approved these changes

2023-07-22 19:59 UTC, Serdaro commented
@JamesHazelcast , @angelasimms, thank you for the content and review.
I believe this topic deserves a bit deeper insight in the Synchronizing Data Across Clusters section of the Platform documentation, since the System Properties section is mostly a reference.

If it is a fine-tuning feature (which I think it is, since the defaults are `false`), you can open up a "Replicating Map/Cache Evictions" or simply "Replicating Evictions" subsection under the Fine-Tuning WAN Replication section.

The content for this new section can talk about why the user may need to enable eviction replications (with some basic scenarios), in what ways it can affect the data consistency when enabled and in use, which points to be taken into consideration in terms of "use with caution", and finally an example WAN replication configuration containing these new properties.

2023-07-24 10:20 UTC, JamesHazelcast commented
Great suggestion @Serdaro, thank you.

I've made a commit which adds more in-depth documentation as you suggested. Please let me know if you'd like any further changes made 👍

2023-07-24 19:10 UTC, Serdaro reviewed
Minor comments.

2023-07-24 19:10 UTC, Serdaro commented on docs/modules/wan/pages/tuning.adoc
> +important to note that this **does not guarantee full data consistency**.
Awesome content @JamesHazelcast , thanks a lot.
I'd suggest to move the very first sentence of this section to here (right before the configuration examples), with a minor editing:

"You can enable the replication of `IMap` and `ICache` evictions to the other clusters by setting the `hazelcast.wan.replicate.imap/icache.evictions` property to `true`, as shown below."

2023-07-24 19:10 UTC, Serdaro commented on docs/modules/wan/pages/tuning.adoc
> +between clusters, however it should be used with caution: source clusters with eviction enabled should replicate to
```suggestion
between clusters. However, you should use it with caution; source clusters with eviction enabled should replicate to
```

2023-07-24 19:10 UTC, Serdaro commented on docs/modules/wan/pages/tuning.adoc
> +====
And, after the configuration examples, we can give the reference to the System Properties content:

"You can find the specifications of these properties in xref:ROOT:system-properties.adoc[System Properties]."

2023-07-31 20:07 UTC, Serdaro approved these changes

2023-08-08 20:29 UTC, Serdaro commented
Let's merge this just before Platform 5.3.2 is released.

2023-08-21 10:57 UTC, merged