Update getting started Docker run command
hazelcast/hz-docs pull request #806
Opened 2023-07-20 13:25 UTC by JackPGreen

Add HZ_NETWORK_PUBLICADDRESS to Docker run command

Fixes https://github.com/hazelcast/hz-docs/issues/805

2023-07-20 21:49 UTC, frant-hartm requested changes
Let's discuss how to approach this.

Ideally, I would like to see
- same recommendation in all places where we document how to start a docker image
- when we use the `-p` parameters we need to add the `HZ_NETWORK_PUBLICADDRESS` env variable, but the `-p` parameter is not needed on Linux, user just needs to use the container address instead of localhost, it is probably enough to have the parameter everywhere and have a note for the Linux users, they will work out the rest
- using `-p 5701:5701` is actually bad advice - it exposes the port on all interfaces, e.g. making it available from wifi, very risky e.g. on a conference wifi setup, this should bind to localhost only, cc @kwart

2023-07-20 21:49 UTC, frant-hartm commented on docs/modules/getting-started/pages/get-started-docker.adoc
> +    -e HZ_NETWORK_PUBLICADDRESS=<host_ip>:5701 \
Shouldn't this match the `5702` in the `-p` parameter below?

2023-07-20 22:07 UTC, JackPGreen commented
> Ideally, I would like to see

Thanks for your feedback :)

> same recommendation in all places where we document how to start a docker image

I'm not sure what you mean by this? I do agree the ~~duplication~~ triplication is the cause of this issue.

> when we use the -p parameters we need to add the HZ_NETWORK_PUBLICADDRESS env variable, but the -p parameter is not needed on Linux, user just needs to use the container address instead of localhost, it is probably enough to have the parameter everywhere and have a note for the Linux users, they will work out the rest

I *personally* think that it's easier to have one command that works on any platform - especially in a getting started document - but I was trying to address the inconsistency rather than improve the readability of the document.

> using -p 5701:5701 is actually bad advice - it exposes the port on all interfaces, e.g. making it available from wifi, very risky e.g. on a conference wifi setup, this should bind to localhost only

If this is the case, should the [Docker hub page](https://hub.docker.com/r/hazelcast/hazelcast) also be updated?

2023-07-21 08:37 UTC, angelasimms requested changes
Hi Jack, Could you also make sure that you add the appropriate release labels to the PR. It looks like this content is in all versions back to version 5.0.

2023-07-21 09:28 UTC, frant-hartm commented
We have multiple places in docs with `docker run hazelcast/hazelcast....`. We should have the same command in all places. I agree it's simpler to have the same command everywhere. I would just add a note to the getting started section that on Linux you can instead do something simpler.

So each `docker run ` should have 
- `-e HZ_NETWORK_PUBLICADDRESS=<host_ip>:5701`
- `-p 5701:5701` or maybe `-p 127.0.0.1:5701:5701`

unless there is a reason for a different setup (e.g. the deploying with docker page is different).

The Docker hub page (hazelcast-docker readme) should be updated as well.

2023-07-21 10:24 UTC, ldziedziul commented
> * using `-p 5701:5701` is actually bad advice - it exposes the port on all interfaces, e.g. making it available from wifi, very risky e.g. on a conference wifi setup, this should bind to localhost only, cc @kwart

but it's just a tutorial I would keep it simple, instead we can mention it's a production config

2023-07-21 10:24 UTC, ldziedziul commented on docs/modules/getting-started/pages/get-started-docker.adoc
> +    -e HZ_NETWORK_PUBLICADDRESS=<host_ip>:5701 \
I would mention why we need this setting or point the documentation

2023-07-21 11:07 UTC, kwart requested changes
Both, @frant-hartm and @ldziedziul are right. Exposing the port to the public has security implications, but we should keep the commands as simple as possible.

I suggest adding a warning Notice at the beginning of the tutorial describing the implications. I.e. Other computers on the network can connect to the exposed port and
* manipulate data in the cluster,
* execute jobs in the running member containers;
* manage the cluster (e.g. shut down members)

2023-07-26 10:56 UTC, JackPGreen commented
> Hi Jack, Could you also make sure that you add the appropriate release labels to the PR? It looks like this content is in all versions back to version 5.0. Thanks again.

Done, thanks :)

2023-07-26 11:07 UTC, JackPGreen commented
> We have multiple places in docs with `docker run hazelcast/hazelcast....`. We should have the same command in all places. I agree it's simpler to have the same command everywhere. 

I did try changing everywhere but it got a bit silly - e.g. the [logging examples](https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/logging#logging-pattern) don't need it.
So I've just added it everywhere a `HZ_CLUSTERNAME` is used as that seems somewhere logical another member might be used as well.

2023-07-26 17:09 UTC, JackPGreen commented
> I would just add a note to the getting started section that on Linux you can instead do something simpler.

I've not done this - I think for consistency you'd need to add it to every `docker run` reference, there's no guarantee a user will start at `Getting started` - and I think it's easier to have simpler common instructions.

Maybe a compromise can be some slightly more technical description in in the `Deploying` section that talks about what `-p` actually does, the security implications and also that it's not needed on Linux? But I think that's probably beyond the scope of this change (and also I don't know enough to write it...)

> Both, @frant-hartm and @ldziedziul are right. Exposing the port to the public has security implications, but we should keep the commands as simple as possible.
> 
> I suggest adding a warning Notice at the beginning of the tutorial describing the implications. I.e. Other computers on the network can connect to the exposed port and
> 
> * manipulate data in the cluster,
> * execute jobs in the running member containers;
> * manage the cluster (e.g. shut down members)

Thanks - I've added something, not sure if it's what you had in mind.

2023-08-01 07:03 UTC, kwart approved these changes

2023-08-01 07:09 UTC, frant-hartm approved these changes

2023-08-01 09:48 UTC, merged