TO_CHAR conversion function.
hazelcast/hz-docs pull request #930
Opened 2023-12-15 11:09 UTC by Serdaro

2023-12-15 11:13 UTC, rebekah-lawrence approved these changes
LGTM

2024-03-06 10:25 UTC, burakgok requested changes

2024-03-06 10:25 UTC, burakgok commented on docs/modules/sql/pages/functions-and-operators.adoc
> +The `FM` pattern enables the fill mode, which suppresses padding.
```suggestion
The `FM` pattern enables _the fill mode_, which suppresses padding.
```

2024-03-06 10:27 UTC, burakgok approved these changes

2024-03-06 10:27 UTC, rebekah-lawrence commented
@burakgok - out of curiosity, why the italics?

2024-03-06 10:53 UTC, burakgok commented
@rebekah-lawrence The term "fill mode" was coined by Oracle and is very counter-intuitive. When you enable it, it suppresses padding, so the output takes the minimum amount of space possible, which is the exact opposite of what I expect from "the fill mode". The reason we use it in our documentation is to facilitate the migration from Oracle to Hazelcast SQL.

2024-03-06 10:55 UTC, rebekah-lawrence commented
Thanks @burakgok - a new bit of knowledge to add to my brain. Much appreciated.

2024-03-06 11:28 UTC, merged