[CN-1101] Update Adding Custom Jar Page
hazelcast/hz-docs pull request #986
Opened 2024-02-01 14:17 UTC by cagric0

Since the old suggested way for adding custom jar is not the best practice and it's complicated, we wanted to promote Hazelcast Platform Operator User Code Deployment(UCD) feature. And suggest the basic solution which is custom docker image to our users. Here is the updated version of the page:
 
<img width="1104" alt="Screen Shot 2024-02-01 at 5 07 38 PM" src="https://github.com/hazelcast/hz-docs/assets/44342412/d916b00a-3a07-4046-91bf-9e239cdb6159">

2024-02-01 16:47 UTC, rebekah-lawrence requested changes

2024-02-01 16:47 UTC, rebekah-lawrence commented on docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
> +NOTE: We highly recommend you to use Hazelcast Platform Operator's xref:operator:ROOT:user-code-deployment.adoc[User Code Deployment] feature if you need to add custom jar to your Hazelcast members.
```suggestion
NOTE: We strongly recommend that you use Hazelcast Platform Operator's xref:operator:ROOT:user-code-deployment.adoc[User Code Deployment] feature if you need to add a custom JAR to your Hazelcast members.
```

2024-02-01 16:47 UTC, rebekah-lawrence commented on docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
> +If you'd like to add custom JAR files to the Platform/Management Center, you can extend the Hazelcast/Management Center base image and provide your configuration file or/and custom JARs.
```suggestion
If you want to add custom JAR files to the Platform and/or Management Center, you can extend the the relevant Center base image and provide your configuration file and/or custom JARs.
```

2024-02-01 16:47 UTC, rebekah-lawrence commented on docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
> +To do that, you need to create a new `Dockerfile` and build it with `docker build` command.
```suggestion
To do this, you must create a new `Dockerfile` and build it using the `docker build` command.
```

2024-02-01 16:47 UTC, rebekah-lawrence commented on docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
> +In the `Dockerfile` example below, we are creating a new image based on the Hazelcast image and adding a custom JAR
```suggestion
In the `Dockerfile` example below, we create a new image based on the Hazelcast image and add a custom JAR
```

2024-02-02 07:30 UTC, hasancelik approved these changes

2024-02-05 11:00 UTC, rebekah-lawrence approved these changes
LGTM

2024-02-05 11:09 UTC, merged